### ISSUE TITLE
Something went wrong with d.update

### ISSUE THREAD

**Issue by pfeducode** [shubham-goel/ds#4]
![2022-10-15_11-57](https://user-images.githubusercontent.com/100210045/195967871-533bfd5c-8368-459a-8ecb-ab007af06167.png)

### The last update dimension of t is [12,2]
![2022-10-15_11-56](https://user-images.githubusercontent.com/100210045/195967877-e895eca8-194d-4d11-9856-34f37dcf27be.png)
Could you give me some suggestions

**Comment by Matt-V50** [comment]
Same issue here.

**Comment by Matt-V50** [comment]
Maybe we should use 
```python
cam_metrics.update(loss_tensor_to_dict(fov_l1.mean(axis=1), prefix='fov/'))
```
to instead?
https://github.com/shubham-goel/ds/blob/2ef898894abb33c82e73790eedf30995ddc9d1c1/src/utils/metrics.py#L70-L71

**Comment by shubham-goel** [comment]
Hi, thanks for the issue! 

This error arises because your camera objects are storing `focal_length` as a tuple `(f_x, f_y)` instead of just `f`. This could be because of a Pytorch3D version update, but it's an easy fix. Following @FavorMylikes's suggestion above, please add the following before [line 71](https://github.com/shubham-goel/ds/blob/2ef898894abb33c82e73790eedf30995ddc9d1c1/src/utils/metrics.py#L70-L71):

```python
if fov_l1.dim() == 2: 
    fov_l1= fov_l1.mean(axis=1)
```

I've also committed this change to the code. Thank you!

**Comment by pfeducode** [comment]
thank you, it works well
